### ISSUE TITLE
1.20 no hex

### ISSUE THREAD

**Issue by OwOsucksAwesomeMinecraftbossAlissha6TRM** [SamsTheNerd/ducky-periphs#24]
if you try to craft planks with hex not installed, your game crashes

**Comment by SamsTheNerd** [comment]
just any planks ? do you have the crash log ?

**Comment by OwOsucksAwesomeMinecraftbossAlissha6TRM** [comment]
i tested with only oak planks, lemme send the log

**Comment by OwOsucksAwesomeMinecraftbossAlissha6TRM** [comment]
java.lang.NoClassDefFoundError: at/petrak/hexcasting/api/casting/castables/Action
	at com.samsthenerd.duckyperiphs.peripherals.keyboards.KeyboardRecipe.matches(KeyboardRecipe.java:61) ~[duckyperiphs-1.20.1-1.3.0-forge.jar%23172!/:?] {re:classloading}
	at com.samsthenerd.duckyperiphs.peripherals.keyboards.KeyboardRecipe.m_5818_(KeyboardRecipe.java:22) ~[duckyperiphs-1.20.1-1.3.0-forge.jar%23172!/:?] {re:classloading}
	at net.minecraft.world.item.crafting.RecipeManager.m_220238_(RecipeManager.java:120) ~[server-1.20.1-20230612.114412-srg.jar%23203!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:polymorph.mixins.json:MixinRecipeManager,pl:mixin:A}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[?:?] {}
	at com.google.common.collect.CollectSpliterators$1WithCharacteristics.lambda$forEachRemaining$1(CollectSpliterators.java:72) ~[guava-31.1-jre.jar%2374!/:?] {}
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104) ~[?:?] {}
	at com.google.common.collect.CollectSpliterators$1WithCharacteristics.forEachRemaining(CollectSpliterators.java:72) ~[guava-31.1-jre.jar%2374!/:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?] {}
	at net.minecraft.world.item.crafting.RecipeManager.m_44056_(RecipeManager.java:123) ~[server-1.20.1-20230612.114412-srg.jar%23203!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:polymorph.mixins.json:MixinRecipeManager,pl:mixin:A}
	at com.illusivesoulworks.polymorph.common.capability.AbstractRecipeData.getRecipe(AbstractRecipeData.java:145) ~[polymorph-forge-0.49.0+1.20.1.jar%23189!/:0.49.0+1.20.1] {re:classloading}
	at com.illusivesoulworks.polymorph.common.capability.PlayerRecipeData.getRecipe(PlayerRecipeData.java:57) ~[polymorph-forge-0.49.0+1.20.1.jar%23189!/:0.49.0+1.20.1] {re:classloading}
	at com.illusivesoulworks.polymorph.common.crafting.RecipeSelection.lambda$getRecipe$1(RecipeSelection.java:99) ~[polymorph-forge-0.49.0+1.20.1.jar%23189!/:0.49.0+1.20.1] {re:mixin,re:classloading}
	at java.util.Optional.map(Optional.java:260) ~[?:?] {re:mixin}
	at com.illusivesoulworks.polymorph.common.crafting.RecipeSelection.getRecipe(RecipeSelection.java:99) ~[polymorph-forge-0.49.0+1.20.1.jar%23189!/:0.49.0+1.20.1] {re:mixin,re:classloading}
	at com.illusivesoulworks.polymorph.common.crafting.RecipeSelection.getPlayerRecipe(RecipeSelection.java:78) ~[polymorph-forge-0.49.0+1.20.1.jar%23189!/:0.49.0+1.20.1] {re:mixin,re:classloading}
	at com.illusivesoulworks.polymorph.common.crafting.RecipeSelection.getPlayerRecipe(RecipeSelection.java:70) ~[polymorph-forge-0.49.0+1.20.1.jar%23189!/:0.49.0+1.20.1] {re:mixin,re:classloading}
	at net.minecraft.world.inventory.CraftingMenu.redirect$zcm000$polymorph$getRecipe(CraftingMenu.java:1049) ~[server-1.20.1-20230612.114412-srg.jar%23203!/:?] {re:mixin,re:classloading,pl:mixin:APP:polymorph.mixins.json:AccessorCraftingMenu,pl:mixin:APP:polymorph.mixins.json:MixinCraftingMenu,pl:mixin:A}
	at net.minecraft.world.inventory.CraftingMenu.m_150546_(CraftingMenu.java:66) ~[server-1.20.1-20230612.114412-srg.jar%23203!/:?] {re:mixin,re:classloading,pl:mixin:APP:polymorph.mixins.json:AccessorCraftingMenu,pl:mixin:APP:polymorph.mixins.json:MixinCraftingMenu,pl:mixin:A}
	at net.minecraft.world.inventory.InventoryMenu.m_6199_(InventoryMenu.java:128) ~[server-1.20.1-20230612.114412-srg.jar%23203!/:?] {re:mixin,re:classloading,pl:mixin:APP:polymorph.mixins.json:AccessorInventoryMenu,pl:mixin:A}
	at net.minecraft.world.inventory.TransientCraftingContainer.m_6836_(TransientCraftingContainer.java:68) ~[server-1.20.1-20230612.114412-srg.jar%23203!/:?] {re:classloading}
	at net.minecraft.world.inventory.Slot.m_5852_(Slot.java:63) ~[server-1.20.1-20230612.114412-srg.jar%23203!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.inventory.Slot.m_269060_(Slot.java:59) ~[server-1.20.1-20230612.114412-srg.jar%23203!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.inventory.Slot.m_150656_(Slot.java:165) ~[server-1.20.1-20230612.114412-srg.jar%23203!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.inventory.AbstractContainerMenu.m_150430_(AbstractContainerMenu.java:410) ~[server-1.20.1-20230612.114412-srg.jar%23203!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.inventory.AbstractContainerMenu.m_150430_(AbstractContainerMenu.java:340) ~[server-1.20.1-20230612.114412-srg.jar%23203!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.inventory.AbstractContainerMenu.m_150399_(AbstractContainerMenu.java:294) ~[server-1.20.1-20230612.114412-srg.jar%23203!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_5914_(ServerGamePacketListenerImpl.java:1550) ~[server-1.20.1-20230612.114412-srg.jar%23203!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:badpackets.mixins.json:MixinServerGamePacketListenerImpl,pl:mixin:APP:cpm.mixins.json:ServerGamePacketListenerImplMixin,pl:mixin:A}
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.m_5797_(ServerboundContainerClickPacket.java:56) ~[server-1.20.1-20230612.114412-srg.jar%23203!/:?] {re:classloading}
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.m_5797_(ServerboundContainerClickPacket.java:12) ~[server-1.20.1-20230612.114412-srg.jar%23203!/:?] {re:classloading}
	at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22) ~[server-1.20.1-20230612.114412-srg.jar%23203!/:?] {re:classloading}
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.1-20230612.114412-srg.jar%23203!/:?] {re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[server-1.20.1-20230612.114412-srg.jar%23203!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.1-20230612.114412-srg.jar%23203!/:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:770) ~[server-1.20.1-20230612.114412-srg.jar%23203!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[server-1.20.1-20230612.114412-srg.jar%23203!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[server-1.20.1-20230612.114412-srg.jar%23203!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:753) ~[server-1.20.1-20230612.114412-srg.jar%23203!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:747) ~[server-1.20.1-20230612.114412-srg.jar%23203!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:139) ~[server-1.20.1-20230612.114412-srg.jar%23203!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:733) ~[server-1.20.1-20230612.114412-srg.jar%23203!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:665) ~[server-1.20.1-20230612.114412-srg.jar%23203!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23203!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {re:mixin}
Caused by: java.lang.ClassNotFoundException: at.petrak.hexcasting.api.casting.castables.Action
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.10.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.10.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	... 47 more

**Comment by OwOsucksAwesomeMinecraftbossAlissha6TRM** [comment]
should of said its a hex casing API issue

**Comment by OwOsucksAwesomeMinecraftbossAlissha6TRM** [comment]
i was thinking compiling hex would fix it, but i tried to compile hex and it said git finished with non-zero exit value 128, thought it was because i didnt have git installed, not the issue, but anyway

**Comment by OwOsucksAwesomeMinecraftbossAlissha6TRM** [comment]
please tell when you do that, so I so I can compile the mod when you do

**Comment by SamsTheNerd** [comment]
fixed in v1.3.1 (it's on modrinth and curseforge, no need to compile)
